### ISSUE TITLE
Adding Alive/Dead Player Count Trackers

### ISSUE THREAD

**Issue by tydood** [tydood/clocktowertimer#18]
Eventually, I would like to be able to give users the option to select how many players they have in their game and it will update the default timer (to be either less than 10 min or more, depending on player count).

When considering how I wanted to implement this, I thought it might be nice to add some information that would normally be displayed on the town square board. This would allow the players and the storyteller to more easily see how many alive/dead/dead players with votes there are currently. I could also have the timer update based on the amount of alive players left. Something like this:

![CleanShot 2024-02-28 at 09 58 04@2x](https://github.com/tydood/clocktowertimer/assets/153012987/2eea888d-7057-4543-84f3-5a669568f97a)

@dennisschuerholz Do you have any feedback on this? Good idea, bad idea? Any changes?

**Comment by dennisschuerholz** [comment]
I like this idea.
I also thought of adding the "role distribution" e.g. 11 players (excluding travellers) meaning (7 townsfolk, 1 outsider, 2 minions, 1 demon). That would also normally be placed in townsquare. That of course is independent from the alive player count. That was the next thing on my list of ideas: Starting Player count and therefore adjusting the initial timer and displaying the distribution table.

For this we could do sth like:

- Input player count (excluding travellers) at start of the game and set the role distribution board
- Set alive player count (apc) to this number
- Button (and Hotkey) to increment and decrement apc (death/resurrection and traveller interactions)
- Update timer to e.g. apc minutes on each change of apc (or another number close to apc)
- Both features (role ditribution and apc) might be too much going on on the screen for some people so it might be toggleable like the info dialogue

Additional things to consider:

- ~I'm still experimenting how much time is perfect. 15 Minute day 1 is too long even for 15 Players, but 5 Minutes day 1 is also short for a 5 player teensy... So minutes per day = alive players is not that good. I don't have the perfect formula (yet).~
- EDIT: Just as I wrote #19 it came to my mind: We don't need a formula.. We ony need the same array(s) we currently use but instead of the night as key we use the apc. Silly me.
- we need 2 buttons for killing/resurrecting players
- dead player votes will need 2 additional buttons as one may "get back" their ghost vote (due to error or ferryman fabled)
- so there's potential for a cluttered UI
- I don't know if we really need to display the counter for dead players - but it could be helpfull
- as traveller get counted as alive player for voting but are excluded from evil winning condition (2 players alive) would we have to distinguish normal characters and traveller in the alive player count?

**Comment by tydood** [comment]
@dennisschuerholz I love this. It seems like this could be broken apart into 3 additions:

### Player Count Trackers
One thing that you mentioned and that I agree with is that the storyteller may not want to keep track of the digital player count trackers in addition to the tokens on the physical town square board. We could have the option to hide it, but then we would need the timer to once again be updated based on the current day as opposed to the APC. I'm not entirely opposed to this. Here's maybe why we should keep it tied to the timer:
* If we required the user to input a starting player count, the timer would most likely be accurate based on what day it is, even factoring in multiple deaths/no execution. 
* Implementation would be much easier
* I like the idea of the timer being updated automatically when the days progress as opposed to forcing the user to update it with the APC (we could then include the option to hide ALL town square information).
* I think it would be best if the timer got shorter even if there are no deaths that day. We never want the timer to go up, and it might if someone is resurrected (if it is tied to APC)
* If we end up allowing the user to choose custom times, I think it would make more sense if that was fixed to the day as opposed to player count. 

However, I could be persuaded otherwise! If we kept it to the timer, implementing these buttons would be quite easy as there would be no logic tied to the APC. 

Either way, my idea on the buttons was to be able to right click it to increase the count and left click it to decrease. It wouldn't be very obvious (we'd have to include something in the information box) but it would clean up the UI quite a bit.

---

### Player Distribution Information
This should be fairly easy to implement, it would be static and determined by the SPC (starting player count). Mostly design/UI here.

---

### Starting Player Count Input
This should almost be required before starting, because it will update the following:
* The default array for the timer will need to be adjusted based on this information. If we decide to keep it to the timer, we would just have a default array for each possible SPC. If we decide to keep the timer locked to the APC, then we would skip this step.
* This would update the APC tracker
* It would also update the player distribution information. 

Couple ideas on implementation
1. Make it obvious: put a big button right at the top or a prompt when you first land on the site
2. Hide it in the settings: but lock the timer until that information is set

Let's not do the dead player count, I don't think there is a need for it. Maybe the third tracker could be for travelers with votes left? I like this because then we wouldn't have to include another option for displaying the amount of Travelers in the player distribution information.

**Comment by tydood** [comment]
I'm closing this out, I believe everything in this ticket has been added to the app.
