### ISSUE TITLE
Keyboard Shortcuts dead/alive/vote

### ISSUE THREAD

**Issue by dennisschuerholz** [tydood/clocktowertimer#33]
I need to impement some keyboard shortcuts on these feature.

(Very small change, I will implement it at some point in the near future - thought on the keys to use?)

**Comment by tydood** [comment]
Maybe:

'H' - Resurrect (heart/life)
'D' - Player death (would have to change mute, maybe to 'M'?)
'V' - Ghost Vote

Some clarification as to why I removed the "add vote" button. It is my understanding that if I player is resurrected, they will also get their ghost vote back. So instead of having two buttons, I just kept the one. Resurrecting adds 1 to player count AND to vote count.

**Comment by dennisschuerholz** [comment]
Ah! That issues a bug i think:
A resurrected dead player may not have used their Ghost Vote (indeed most of the time they would not). Say we have 12 Players. One dies: 11 alive, 12 votes. One is resurrected: 12 alive, 13 votes?!
Hot fix ist to decrease the vote manually afterwards..

I Like the current simplicity thought...

**Comment by tydood** [comment]
Ahh, I should have thought of that. Nice catch. I am trying to think of a way to clean up the amount of buttons, but I don't think there is a way without removing some functionality.

I think I'll re-add the add vote button and remove the +1 increase on the vote count when pressing resurrect. I'm currently working on making a way to hide the whole tray, and I will probably move the settings buttons at the top to the bottom (no point in having two trays to hide).
